reducing action size using reusable workflow

diff --git a/.github/actions/dev-ipfs-pin/action.yml b/.github/actions/dev-ipfs-pin/action.yml
--- a/.github/actions/dev-ipfs-pin/action.yml
+++ b/.github/actions/dev-ipfs-pin/action.yml
@@ -16,31 +16,16 @@ inputs:
   GKE_CLUSTER_REGION:
     description: ''
     required: true
-  IPFS_PRIMARY_SERVER_PORT:
+  PINATA_HASH:
     description: ''
     required: true
-  IPFS_SECONDARY_SERVER_PORT:
+  IPFS_SERVER_PORT:
     description: ''
     required: true
-  IPFS_PRIMARY_SERVER:
+  IPFS_SERVER:
     description: ''
     required: true
-  IPFS_SECONDARY_SERVER:
-    description: ''
-    required: true
-  IPFS_PRIMARY_SERVER_KEY:
-    description: ''
-    required: true
-  IPFS_SECONDARY_SERVER_KEY:
-    description: ''
-    required: true
-  IPFS_TERTIARY_SERVER_PORT:
-    description: ''
-    required: true
-  IPFS_TERTIARY_SERVER:
-    description: ''
-    required: true
-  IPFS_TERTIARY_KEY:
+  IPFS_SERVER_KEY:
     description: ''
     required: true
 
@@ -73,6 +58,9 @@ runs:
           ipfs add -rQ --cid-version=1 --pin=false ./${{ inputs.BUILD_PATH }}/ && \
           rm -rf ./app.tar.gz ./${{ inputs.BUILD_PATH }}')"
 
+        test "${IPFS_HASH}" = '${{ inputs.PINATA_HASH }}' || \
+          { echo -e "Hashes differ, aborting pinning\nPINATA: ${{ inputs.PINATA_HASH }}\nLOCAL: ${IPFS_HASH}" && exit 1; }
+
         echo "Pinning to cluster..."
         kubectl -n ipfs-cluster exec -i ${POD_NAME} -c ipfs-cluster -- \
           ipfs-cluster-ctl pin add --wait --wait-timeout=180s \
@@ -84,10 +72,9 @@ runs:
       continue-on-error: false
       shell: bash
       run: |
-        echo -n "${{ inputs.IPFS_PRIMARY_SERVER_KEY }}" | base64 -d >> ./p_key
-        echo -n "${{ inputs.IPFS_SECONDARY_SERVER_KEY }}" | base64 -d >> ./s_key
-        echo -n "${{ inputs.IPFS_TERTIARY_KEY }}" | base64 -d >> ./key
-        chmod 400 ./p_key ./s_key ./key
+        rm -rf ./key
+        echo -n "${{ inputs.IPFS_SERVER_KEY }}" | base64 -d >> ./key
+        chmod 400 ./key
 
     - name: Upload build to IPFS Primary Server
       id: ipfs-scp-primary
@@ -96,34 +83,10 @@ runs:
       run: |
         scp -o StrictHostKeyChecking=no \
         -i ./p_key \
-        -P \${{ inputs.IPFS_PRIMARY_SERVER_PORT }} app.tar.gz ipfs@\${{ inputs.IPFS_PRIMARY_SERVER }}:.
+        -P \${{ inputs.IPFS_SERVER_PORT }} app.tar.gz ipfs@\${{ inputs.IPFS_SERVER }}:.
         ssh -o StrictHostKeyChecking=no \
-        -p \${{ inputs.IPFS_PRIMARY_SERVER_PORT }} \
-        -i ./p_key ipfs@\${{ inputs.IPFS_PRIMARY_SERVER }} "tar zxf app.tar.gz  && ipfs add -rQ --cid-version=1 ./${{ inputs.BUILD_PATH }}/"
-
-    - name: Upload build to IPFS Secondary Server
-      id: ipfs-scp-secondary
-      continue-on-error: false
-      shell: bash
-      run: |
-        scp -o StrictHostKeyChecking=no \
-        -i ./s_key \
-        -P \${{ inputs.IPFS_SECONDARY_SERVER_PORT }} app.tar.gz ipfs@\${{ inputs.IPFS_SECONDARY_SERVER }}:.
-        ssh -o StrictHostKeyChecking=no \
-        -p \${{ inputs.IPFS_SECONDARY_SERVER_PORT }} \
-        -i ./s_key ipfs@\${{ inputs.IPFS_SECONDARY_SERVER }} "tar zxf app.tar.gz  && ipfs add -rQ --cid-version=1 ./${{ inputs.BUILD_PATH }}/"
-
-    - name: Upload build to IPFS Tertiary Server
-      id: ipfs-scp-tertiary
-      continue-on-error: false
-      shell: bash
-      run: |
-        scp -o StrictHostKeyChecking=no \
-        -i ./key \
-        -P \${{ inputs.IPFS_TERTIARY_SERVER_PORT }} app.tar.gz ipfs@\${{ inputs.IPFS_TERTIARY_SERVER }}:.
-        ssh -o StrictHostKeyChecking=no \
-        -p \${{ inputs.IPFS_TERTIARY_SERVER_PORT }} \
-        -i ./key ipfs@\${{ inputs.IPFS_TERTIARY_SERVER }} "tar zxf app.tar.gz  && ipfs add -rQ --cid-version=1 ./${{ inputs.BUILD_PATH }}/"
+        -p \${{ inputs.IPFS_SERVER_PORT }} \
+        -i ./p_key ipfs@\${{ inputs.IPFS_SERVER }} "tar zxf app.tar.gz  && ipfs add -rQ --cid-version=1 ./${{ inputs.BUILD_PATH }}/"
 
     - name: Clean build and tmp directory on Servers
       continue-on-error: false
@@ -131,12 +94,5 @@ runs:
       shell: bash
       run: |
         ssh -o StrictHostKeyChecking=no \
-        -p \${{ inputs.IPFS_PRIMARY_SERVER_PORT }} \
-        -i ./p_key ipfs@\${{ inputs.IPFS_PRIMARY_SERVER }} "rm -rf ./${{ inputs.BUILD_PATH }}/"
-        ssh -o StrictHostKeyChecking=no \
-        -p \${{ inputs.IPFS_SECONDARY_SERVER_PORT }} \
-        -i ./s_key ipfs@\${{ inputs.IPFS_SECONDARY_SERVER }} "rm -rf ./${{ inputs.BUILD_PATH }}/"
-        ssh -o StrictHostKeyChecking=no \
-        -p \${{ inputs.IPFS_TERTIARY_SERVER_PORT }} \
-        -i ./key ipfs@\${{ inputs.IPFS_TERTIARY_SERVER }} "rm -rf ./${{ inputs.BUILD_PATH }}/"
-        rm -rf ./p_* ./s_* ./ke*
+        -p \${{ inputs.IPFS_SERVER_PORT }} \
+        -i ./p_key ipfs@\${{ inputs.IPFS_SERVER }} "rm -rf ./${{ inputs.BUILD_PATH }}/ app.tar.gz"
